---
# --- Metadatos Básicos ---
title: "Análisis Descriptivo del Ranking ATP como Indicador de Éxito en el Tenis de Élite (2015-2025)"
author:
   - Andrés Ortega
   - Marco Ramirez
date: "Abril 2026"

# --- Metadatos Específicos de Plantilla ---
degree: "Computación I"
director: 
  - Jesus Ochoa 
  - Oliver Triveño
lugar: "Caracas"
facultad: 
  - Facultad de Ciencias Económicas y Sociales
  - Escuela de Estadistica y Ciencias Actuariales
# Ruta al escudo (relativa al archivo .Rmd)
escudo: "Latex/Classes/Escudos/faces"

# --- Bibliografía ---
bibliography: bibliografia.bib

# --- Configuración de Salida ---
output: 
  pdf_document:
    template: template.tex  # Llamamos al archivo de plantilla
    keep_tex: true                 # Útil para ver errores si ocurren
    toc: true                      # Generar índice
    number_sections: true
    citation_package: natbib       # Importante: forzar natbib porque tu plantilla lo usa

# --- Resumen (Abstract) ---
abstract: |
  Resumen del trabajo de investigación...
---

```{r setup, include=FALSE}
# Configuración global de chunks
knitr::opts_chunk$set(
  echo = FALSE,        # Mostrar código
  warning = FALSE,    # Ocultar advertencias
  message = FALSE,    # Ocultar mensajes de carga
  fig.align = "center",
  out.width = "90%",
  fig.pos = "H",
  out.extra = ""
)

# Cargar librerías necesarias
library(tidyverse)
library(knitr)
library(kableExtra)
library(scales)
```

\chapter*{Introducción}

En el área del deporte profesional, la recopilación y análisis de datos históricos es una tarea fundamental para generar estadísticas descriptivas que permitan recopilar información relevante del rendimiento de un jugador o equipo. A diferencia de los deportes jugados en equipo dónde las estadísticas pueden llegar a atenuarse por el desempeño grupal, en el caso del tenis, debido a su estructura de competición individual (single), cada dato (puntos obtenidos, ranking, cantidad de sets jugados) manifiesta el desempeño individual de cada atleta.  A menudo, se asume que el ranking de un jugador en un partido es una métrica clave la cual expresa cual es la tendencia de quien pueda llegar a ser el ganador, sin embargo, existen otras variables como (ronda del torneo, superficie de la cancha, tipo de serie) las cuales pueden llegar a influir en el desempeño de jugadores y dejan un lado al ranking ATP como factor determinante.


Por lo tanto, este estudio busca responder la siguiente pregunta: ¿Es el ranking de un jugador una métrica suficiente para reflejar lo que sucederá en cancha?

\chapter{Planteamiento del Problema}

 En el tenis profesional, el ranking ATP es la métrica oficial que mide el éxito y el desempeño de los jugadores. Este sistema no solo determina quiénes son los mejores del mundo, sino que también condiciona la participación en torneos, la asignación de cabezas de serie y las expectativas del público. Ser parte del top 50 no solo garantiza notoriedad en el tenis, sino que te ofrece otros beneficios como el acceso a torneos de mayor categoría, una exposición constante a diferentes superficies y prestigio en la carrera deportiva.

Ahora bien, ¿Es el ranking ATP una métrica suficiente para comparar a dos jugadores que compiten en cancha? Además, ¿En qué superficie el ranking ATP es más representativo? En el presente trabajo describiremos cómo se comporta el top 50 de jugadores en diferentes superficies, rondas y torneos en un histórico comprendido entre 2016-2025 en la época dorada del tenis.\

Argumento final. Debido a esto, se plantea las siguientes preguntas de investigación:\


\textbf{1.}	¿Cómo se comporta el ranking de los ganadores y perdedores en el ATP tour?\

\textbf{2.}	¿En qué torneos se enfocan los jugadores con rankings más altos y más bajos?\

\textbf{3.}	¿Cúal es el ranking promedio predominante en las finales de los torneos más importantes?\


\section{Justificación}

La justificación del presente trabajo se sustenta en evaluar la robustez del Ranking ATP como un descriptor del desempeño real en el tenis profesional.

En el ámbito deportivo, el ranking de un jugador es una métrica acumulativa de resultados pasados ​​que definen su estatus en el circuito. Esta investigación busca que por medio de la estadística descriptiva identificar los patrones de distribución de los ganadores y perdedores. Para ello, se tomará como universo en estudio a los partidos de 10 temporadas consecutivas en el período entre 2016-2025 de ambos atletas pertenecientes al top 50, este segmentación se realiza producto a que estos atletas tienen acceso directo a los Grand Slam, Masters 1000 y a una gran parte de los torneos ATP 500 y ATP 250.

En el ámbito académico, este trabajo se inserta en la formación de la Escuela de Estadística y Ciencias Actuariales, demostrando la capacidad del lenguaje de programación R para el manejo de grandes volúmenes de datos y la generación de reportes dinámicos mientras que el entorno de Python permite generar reportes interactivos para la visualización e interpretación de los mismos.
\

\section{Objetivos}
 
\subsection{Objetivo General}
\begin{itemize}
  \item{Determinar si existe una relación entre el posicionamiento en el ranking ATP y el desempeño competitivo de los jugadores para evaluar su rendimiento en los partidos según superficie, torneo y ronda en los atletas pertenecientes al Top 50 durante el periodo 2016-2025.}
\end{itemize}

\subsection{Objetivos Específicos}
\begin{itemize}
  \item{Comparar el desempeño de los ganadores y perdedores de los jugadores pertenecientes al top 50 en el período de análisis.}
  \item{Analizar si la posición del ranking de los jugadores varía de manera sustancial de acuerdo a la superficie del partido jugado.}
  \item{Verificar la eficiencia del ranking como pronosticador del éxito mediante el avance en las rondas.}
  \item{Identificar si los jugadores con mejor posicionamiento (Top 10), concentran su participación en eventos con mayor prestigio.}
\end{itemize}


\section{Cobertura}

\subsection{Horizontal}

La cobertura horizontal se basa en cada uno de los partidos de tenis registrados en la base de datos. Se considera el momento, lugar y torneo en el cual se efectuaron los partidos, y el resultado de los mismos junto a ciertas características que describen los enfrentamientos.\

\begin{table}[ht]
\centering
\caption{Variables consideradas en el estudio} 
\label{tab:variables}
\renewcommand{\arraystretch}{1.5} %
\begin{tabularx}{\textwidth}{llX} %
  \hline
\textbf{TIPO} &\textbf{VARIABLE} &\textbf{DESCRIPCIÓN}\\ 
  \hline
Categórica & Tournament & Nombre oficial del torneo dónde se disputo el encuentro\\ 
Numérica & Date & Fecha en la que se llevo a cabo el partido(Formato AAAA-MM-DD)\\
Categórica & Series & Categoría o nivel del torneo\\
Categórica & Surface & Tipo de suelo de la cancha: Duro (Hard), Arcilla (Clay) o Hierba (Grass)\\
Categórica & Round & Etapa eliminatoria del torneo\\
Categórica & Player\_1 & Nombre del primer jugador registrado en el encuentro\\
Categórica & Player\_2 & Nombre del segundo jugador registrado en el encuentro\\
Categórica & Winner & Nombre del jugador que resultó victorioso en el encuentro\\
Categórica & Rank\_1 & Posición en el ranking ATP del Jugador 1 al iniciar el torneo\\
Categórica & Rank\_2 & Posición en el ranking ATP del Jugador 2 al iniciar el torneo\\
Numérica & Tasa de Victorias & Porcentaje de victorias anuales de cada jugador por temporada\\ 
   \hline
\end{tabularx}
\end{table}

\subsection{Vertical}

La cobertura vertical del trabajo de investigación comprende un total de 66790 observaciones. Cada fila representa un partido único jugado en el ATP tour. El alcance temporal de los datos en longitudinal, abarcando desde el año 2000 hasta principios del 2026, lo que permite un análisis del desempeño de jugadores de diferentes épocas y con distintos estilos de juego.


\section{Periodo de Referencia}

Describir la fuente y el Periodo de Referencia utilizado en el trabajo de investigación

\section{Variables}

Las dos variables principales en el estudio (Variables dependientes/objetivo) son Rank_1 y Rank_2, que representa el ranking ATP de un cada jugador en ese juego específico, como variables explicativas o independientes se analizan:


\chapter{Marco Teórico}


\section{Bases Teóricas}

Resumen de las bases teoricas explicadas en el capitulo y su importancia\

\subsection{Definición 1}

Descripción de la definición 1\

\subsection{Definición 2}

Descripción de la definición 2\

\subsection{Definición n}

Descripción de la definición n\


\chapter{Marco Metódico}
En esta sección se presentan las metodologías y/o test necesarios relacionados con la práctica divulgada en el marco teórico, así como las fuentes de datos.
 
\section{Bases metódicas utilizadas en el trabajo de investigación}

Desarrollo\

\subsection{Item 1}

Descripción\

\subsection{Item 2}

Descripción\

\subsubsection{Item 2.2}

Descripción\

\subsection{Item n}

Descripción\

\chapter{Análisis de Resultados}

{\small Este capítulo presenta los resultados obtenidos al aplicar las metodologías descritas en el capítulo anterior, así como del análisis estadístico descriptivo de las variables estudiadas y las ventajas y desventajas al aplicar dichos tests.}

\section{Presentación de resultados 1}

Descripción\

\section{Presentación de resultados 2}

Descripción\

\section{Presentación de resultados n}

Descripción\

\chapter{Conclusiones y Recomendaciones}

\textbf{1.-} Conclusion 1 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 1 del trabajo de investigación.\

\textbf{2.-} Conclusion 2 del trabajo de investigación.\

\textbf{Recomendación} 
Recomendación 2 del trabajo de investigación.\

\textbf{n.-} Conclusion n del trabajo de investigación.\

\textbf{Recomendación} Recomendación n del trabajo de investigación.\

\appendix
\renewcommand{\thechapter}{\Alph{chapter}}

\chapter{Anexo A}

\chapter{Anexo B}

\chapter{Anexo C}

